# Generated by Django 5.2.4 on 2025-08-03 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('relative_path', models.CharField(max_length=500, verbose_name='相对路径')),
                ('size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='文件哈希')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '模块文件',
                'verbose_name_plural': '模块文件',
                'ordering': ['relative_path'],
                'unique_together': {('relative_path',)},
            },
        ),
        migrations.CreateModel(
            name='ModuleEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑用户')),
                ('module_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modulefile', verbose_name='模块文件')),
            ],
            options={
                'verbose_name': '编辑会话',
                'verbose_name_plural': '编辑会话',
                'unique_together': {('module_file', 'user')},
            },
        ),
    ]
