# Generated by Django 5.2.4 on 2025-08-04 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleeditsession',
            options={'verbose_name': '模块编辑会话', 'verbose_name_plural': '模块编辑会话'},
        ),
        migrations.RemoveField(
            model_name='moduleeditsession',
            name='last_activity',
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模块名称')),
                ('category', models.CharField(choices=[('attention', 'Attention'), ('convolution', 'Convolution'), ('down_up', 'Down&Up'), ('fusion', 'Fusion'), ('head', 'Head'), ('block', 'Block'), ('other', 'Other')], default='other', max_length=20, verbose_name='模块分类')),
                ('description', models.TextField(blank=True, verbose_name='模块描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('auto_detected', models.BooleanField(default=True, verbose_name='自动检测')),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='分类者')),
                ('module_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='modules.modulefile', verbose_name='模块文件')),
            ],
            options={
                'verbose_name': '模块项',
                'verbose_name_plural': '模块项',
                'ordering': ['category', 'name'],
                'unique_together': {('module_file', 'name')},
            },
        ),
    ]
