# Generated by Django 5.2.4 on 2025-08-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_moduleeditsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleitem',
            name='category',
            field=models.CharField(default='other', max_length=50, verbose_name='模块分类'),
        ),
        migrations.CreateModel(
            name='DynamicModuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='分类键')),
                ('label', models.CharField(max_length=100, verbose_name='分类标签')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '动态模块分类',
                'verbose_name_plural': '动态模块分类',
                'ordering': ['key'],
            },
        ),
    ]
