# Generated by Django 5.2.4 on 2025-08-05 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_moduleitem_category_dynamicmodulecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefile',
            name='status',
            field=models.CharField(choices=[('unreviewed', '未审查'), ('available', '可用'), ('unavailable', '不可用')], default='unreviewed', max_length=20, verbose_name='文件状态'),
        ),
        migrations.AddField(
            model_name='modulefile',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态更新时间'),
        ),
        migrations.AddField(
            model_name='modulefile',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated_files', to=settings.AUTH_USER_MODEL, verbose_name='状态更新者'),
        ),
    ]
