# Generated by Django 5.2.4 on 2025-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_codetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicmodulecategory',
            options={'ordering': ['order', 'key'], 'verbose_name': '动态模块分类', 'verbose_name_plural': '动态模块分类'},
        ),
        migrations.AddField(
            model_name='dynamicmodulecategory',
            name='color',
            field=models.CharField(default='primary', max_length=20, verbose_name='颜色主题'),
        ),
        migrations.AddField(
            model_name='dynamicmodulecategory',
            name='icon',
            field=models.CharField(default='fas fa-cube', max_length=50, verbose_name='图标类名'),
        ),
        migrations.AddField(
            model_name='dynamicmodulecategory',
            name='is_selectable',
            field=models.BooleanField(default=True, verbose_name='是否可选择'),
        ),
        migrations.AddField(
            model_name='dynamicmodulecategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序顺序'),
        ),
    ]
