# Generated by Django 5.2.4 on 2025-08-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_migrate_fixed_categories_to_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='风格名称')),
                ('description', models.TextField(blank=True, verbose_name='风格描述')),
                ('code_snippet', models.TextField(verbose_name='代码片段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '模块风格',
                'verbose_name_plural': '模块风格',
                'ordering': ['order', 'name'],
            },
        ),
    ]
