"""
Django settings for eolo_web project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j!a7&dm3pc90z8qqa+pm8xo^za(!t6l2bg@%iz(utat57y39us'

# 环境控制：可以通过环境变量切换模式
# 默认开发模式，适合10人以下的小型项目
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# 允许的主机：开发模式允许所有，生产模式需要指定
if DEBUG:
    ALLOWED_HOSTS = ['*']  # 开发模式：允许任何主机访问
else:
    ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')  # 生产模式：限制主机


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 我们的应用
    'accounts',
    'experiments',
    'datasets',
    'models_manager',
    'modules',  # 模块化管理应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eolo_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 添加模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eolo_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# 简化密码验证：只检查用户名重复，密码至少1位
AUTH_PASSWORD_VALIDATORS = [
    # 移除所有默认验证器，只在表单中进行基本检查
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 设置为中文

TIME_ZONE = 'Asia/Shanghai'  # 设置为中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 生产环境静态文件收集目录
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 用户认证相关设置
AUTH_USER_MODEL = 'accounts.User'  # 指定自定义用户模型
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/experiments/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# GPU和实验管理配置
GPU_CONFIG = {
    # GPU显存使用率阈值（百分比）
    'MEMORY_THRESHOLD': 20.0,
    # nvidia-smi命令超时时间（秒）
    'NVIDIA_SMI_TIMEOUT': 10,
}

# 实验队列调度配置
QUEUE_SCHEDULER_CONFIG = {
    # 队列检查间隔（秒）
    'CHECK_INTERVAL': 60,
    # 是否在应用启动时自动启动调度器
    'AUTO_START': True,
    # 调度器线程名称
    'THREAD_NAME': 'GPUQueueScheduler',
}

# 实验进程监控配置
PROCESS_MONITOR_CONFIG = {
    # 进程状态检查间隔（秒）
    'STATUS_CHECK_INTERVAL': 1.0,
    # 进程监控超时时间（秒）
    'MONITOR_TIMEOUT': 10,
    # 日志监控缓冲大小
    'LOG_BUFFER_SIZE': 4096,
    # 进程终止等待时间（秒）
    'TERMINATION_TIMEOUT': 10,
    # 子进程清理等待时间（秒）
    'CLEANUP_TIMEOUT': 5,
}

# 实验日志配置
EXPERIMENT_LOG_CONFIG = {
    # 实验详情页面显示的最新日志条数
    'RECENT_LOGS_COUNT': 10,
    # 日志级别颜色映射
    'LOG_LEVEL_COLORS': {
        'DEBUG': 'text-muted',
        'INFO': 'text-info',
        'WARNING': 'text-warning',
        'ERROR': 'text-danger',
    },
    # ANSI转义序列清理正则表达式
    'ANSI_ESCAPE_PATTERN': r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])',
}

# 实验状态API配置
EXPERIMENT_API_CONFIG = {
    # 状态API更新间隔（毫秒）
    'STATUS_UPDATE_INTERVAL': 1000,
    # 健康检查间隔（秒）
    'HEALTH_CHECK_INTERVAL': 60,
    # API响应超时时间（秒）
    'API_TIMEOUT': 30,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== EOLO项目路径配置 ==========
# 统一管理所有项目相关路径，避免硬编码绝对路径

# EOLO子项目路径（相对于EOLO-WEB根目录）
EOLO_DIR = BASE_DIR / 'EOLO'

# EOLO配置文件路径
EOLO_CONFIGS_DIR = EOLO_DIR / 'configs'
EOLO_MODEL_CONFIGS_DIR = EOLO_CONFIGS_DIR / 'model'
EOLO_SETTING_CONFIGS_DIR = EOLO_CONFIGS_DIR / 'setting'
EOLO_DATASETS_CONFIGS_DIR = EOLO_CONFIGS_DIR / 'data'
EOLO_MODEL_TEMPLATE_DIR = EOLO_CONFIGS_DIR / 'template'

# EOLO API 路径
EOLO_API_DIR = EOLO_DIR / 'api'
EOLO_MODEL_TEST_SCRIPT = EOLO_API_DIR / 'model_test.py'
EOLO_PATHS_JSON = EOLO_API_DIR / 'paths.json'

EOLO_ULTRALYTICS_WORKPIECES_DIR = Path('/icislab/volume3/benderick/futurama/EOLO-ultralytics/ultralytics/nn/workpieces')

# 模型测试配置
MODEL_TEST_CONFIG = {
    # 测试命令超时时间（秒）
    'TIMEOUT': 60,
    # 默认设备
    'DEFAULT_DEVICE': 'cpu',
    # 是否使用安静模式（抑制uv警告）
    'QUIET_MODE': True,
}
